# -*- coding: utf-8 -*-
"""DSA_Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QzYXdL44fRB_RTBfuMTQTrg07Uv5NHVw
"""

# Write a function that takes an array and square the value and sort it in an ascending order

def sort_array_square_typ1(arr):
  arr = [x**2 for x in arr]
  arr.sort()
  return arr


def sort_array_square_typ2(arr):
  # arr = [x**2 for x in arr.sort()] # This doesn't work
  arr = [x**2 for x in arr]
  arr = sorted(arr)
  return arr

arr1 = [20, 4, 35, 80, -10, 0]
sort_array_square(arr1)

sort_array_square_typ2(arr1)

# arr2 = arr1.sort() # This won't work
arr2 = sorted(arr1)
print(arr2)

reversed(arr1)
print(arr1)

# The above methods were have time complexities of O(nlogn)
# More efficeint method would have O(n)

arr1 = [-10, -1, 0, 5, 20, 30] # Notice that this method only works if the first and last values are either largest

def squared_sorted(arr):
  i,j = 0,len(arr)-1
  arrSort = [0]*len(arr)
  for k in reversed(range(len(arr))):
    if arr[i]**2 > arr[j]**2:
      arrSort[k] = arr[i]**2
      i +=1
    else:
      arrSort[k] = arr[j]**2
      j -=1
  return arrSort

squared_sorted(arr1)

from inspect import FullArgSpec
''' Write a code to check if an array is monntonic or not
    monotonic means either increasing or decreasing with respect to index values
    of the array
'''

# My way
def check_monotonic(arr):
    n = len(arr)
    inc, dec = 0, 0
    for i in range(n - 1):
        if arr[i] > arr[i + 1]:
            dec += 1
        elif arr[i] < arr[i + 1]:
            inc += 1

    if dec == 0:
        print("Monotonic non-decreasing")
    elif inc == 0:
        print("Monotonic non-increasing")
    else:
        print("Not monotonic")


# optimal soluion would be
def is_monotonic(arr):
  increasing = decreasing = True

  for i in range(len(arr)-1):
    if arr[i] < arr[i+1]:
      decreasing = False
    elif arr[i] > arr[i+1]:
      increasing = False

    # Early stopping
    if not increasing and not decreasing:
      print("Not monotonic")

  if increasing:
    print("Monotonic non-decreasing")
  elif decreasing:
    print("Monotonic non-increasing")

arr1 = [0, 23, -4]
print(arr1)
check_monotonic(arr1)

is_monotonic(arr1)

